### ISSUE TITLE
Duplicate repo

### ISSUE THREAD

**Issue by justinormont** [PacktPublishing/Hands-On-Machine-Learning-with-MLNET#1]
This repo seems to be an older version of https://github.com/PacktPublishing/Hands-On-Machine-Learning-With-ML.NET.

Perhaps this one should be set to non-public?

/cc @jcapellman, @JackPackt

**Comment by jcapellman** [comment]
Agreed - https://github.com/PacktPublishing/Hands-On-Machine-Learning-With-ML.NET is the repo all of the code for the book is located
